name: interview_demo
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0
  google_maps_flutter:
  location:
  location_web:
  sqflite:
  path_provider:



dev_dependencies:
  flutter_test:
    sdk: flutter
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  assets:
    - assets/menu_picture/american_food.png
    - assets/menu_picture/award.png
    - assets/menu_picture/bubbletea.png
    - assets/menu_picture/discount.png
    - assets/menu_picture/grocery.png
    - assets/menu_picture/makeup.png
    - assets/menu_picture/market.png
    - assets/menu_picture/taiwanese_food.png
    - assets/favoritestore_picture/燈籠滷味.jpg
    - assets/favoritestore_picture/師園鹽酥雞.jpg
    - assets/favoritestore_picture/胖老爹炸雞.jpg
    - assets/carousel/carousel1.png
    - assets/carousel/carousel2.png
    - assets/carousel/carousel3.png
    - assets/carousel/carousel4.png
    - assets/carousel/carousel5.png
    - assets/recommended/茗香園冰室.jpg
    - assets/recommended/迷克夏.jpg
    - assets/recommended/星巴克.jpg
    - assets/recommended/牛洞食堂.jpg
    - assets/recommended/站食可以.jpg
    - assets/popularPicture/Breakfast and Brunch.jpg
    - assets/popularPicture/Taiwanese.jpg
    - assets/popularPicture/Bubble Tea.jpg
    - assets/popularPicture/Grocery.jpg
    - assets/popularPicture/Latest Deals.jpg
    - assets/popularPicture/Restaurant Rewards.jpg
    - assets/popularPicture/Top Eats.jpg
    - assets/popularPicture/American.jpg
    - assets/pastOrderPicture/Tea top.jpg
    - assets/pastOrderPicture/大台北平價滷味.jpg
    - assets/pastOrderPicture/早餐送起司 小農鮮奶.jpg
    - assets/pastOrderPicture/肯德基.jpg
    - assets/pastOrderPicture/胖老爹炸雞.jpg
    - assets/pastOrderPicture/師園鹽酥雞.jpg
    - assets/pastOrderPicture/閑茗樓.jpg
    - assets/pastOrderPicture/燈籠滷味.jpg
    - assets/店家/竹林雞肉飯/竹林雞肉飯.png
    - assets/店家/竹林雞肉飯/銷魂雞飯.jpg
    - assets/店家/竹林雞肉飯/燙青菜.jpg
    - assets/店家/迷克夏/迷克夏.png
    - assets/店家/迷克夏/冬瓜檸檬.png
    - assets/店家/迷克夏/抹茶拿鐵.png
    - assets/店家/迷克夏/珍珠奶茶.png
    - assets/店家/迷克夏/烏龍拿鐵.png
    - assets/店家/迷克夏/烏龍茶.png
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
